# Generated by Django 3.2 on 2021-04-23 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='anonymous', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('gambar', models.ImageField(upload_to='')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('deskripsi', models.TextField(default='tanpa deskripsi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.author')),
            ],
        ),
    ]
